Practica 02
grupo2utn/frro-soporte-2019-02 pull request #2
Opened 2019-04-25 23:25 UTC by grupo2utn

2019-04-26 13:32 UTC, Franr requested changes

2019-04-26 13:32 UTC, Franr commented on practico_03/ejercicio_01.py
> +import sqlite3
el titulo de la PR dice "Practico 02" pero aca hay soluciones del TP 3, que hacemos? cual de los 2 les considero?

2019-04-26 20:29 UTC, grupo2utn commented on practico_03/ejercicio_01.py
> +import sqlite3
Solo la practica 2. Tuvimos un inconveniente a la hora de subirlo, nos falto el commit. La 3 todavia no la termine.

2019-05-02 20:18 UTC, mac3333 approved these changes
TP2 esta practica bien

2019-05-08 22:37 UTC, merged